baseURL = "/"
title = "云游墨客"
theme = "hugo-up-business"
timeZone = "Asia/Shanghai"
summaryLength = 20
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
enableRobotsTXT = true

[pagination]
pagerSize = 6

[markup]
[markup.goldmark.renderer]
unsafe = true
