[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "技术陪跑"
url = "/services/technical-co-running/"
weight = 2

[[main]]
name = "企业 Agent"
url = "/services/agent-transformation/"
weight = 3

[[main]]
name = "联系我们"
url = "/contact/"
weight = 4

[[footer]]
name = "联系我们"
url = "/contact/"
weight = 1